name = "CartnCodForm"
client_id = "b2cafd271c21b90a630528234402b0a1"
application_url = "https://cartncodform-beryl.vercel.app/admin"
embedded = true

[auth]
redirect_urls = [
  "https://cartncodform-backend.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "https://cartncodform-backend.onrender.com/api/webhooks/compliance"

[access_scopes]
scopes = "read_orders,read_customers,write_customers,read_products"

[app_proxy]
url = "https://cartncodform-backend.onrender.com/apps/cartncodform"
subpath = "cartncodform"
prefix = "apps"

[extensions]
  [[extensions.theme]]
  handle = "cartncodform-push"
  path = "extensions/cartncodform-embed"
