name = "CartnCodForm"
client_id = b2cafd271c21b90a630528234402b0a1
application_url = "https://subsonic-regain-bounce.ngrok-free.dev"
embedded = false

[auth]
redirect_urls = [
  "https://subsonic-regain-bounce.ngrok-free.dev/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_orders,read_customers,write_customers"