name = "CartnCodForm"
client_id = "b2cafd271c21b90a630528234402b0a1"
application_url = "https://cartncodform-backend.onrender.com"
embedded = false

[auth]
redirect_urls = [
  "https://cartncodform-backend.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_orders,read_customers,write_customers"
